### ISSUE TITLE
gzip level 9

### ISSUE THREAD

**Issue by jdalton** [nolanlawson/cost-of-small-modules#3]
The default gzip level is something like`6` but for web stuff I think most use `9`.
The [print-sizes snippet](https://github.com/nolanlawson/cost-of-small-modules/blob/4dacb53a18372eabe33aa4ea0ddf15e8f5a6cecc/bin/print-sizes.sh#L41) could be `$(gzip -c9 dist/$bundler-${i}.min.js | wc -c)`.

**Comment by jdalton** [comment]
OT: I tried with [brotli](https://github.com/google/brotli) with a `--quality 11` and got:

> ||100 modules|1000 modules|5000 modules|
| ---- | ---- | ---- | ---- |
|browserify|     935|    4868|   22621|
|browserify-collapsed|     888|    5050|   20643|
|webpack|     422|    1941|    7244|
|rollup|     174|     801|    2030|
|closure|     158|     762|    3402|

**Comment by nolanlawson** [comment]
Neat! Yeah that's a good point; I should probably try to squeeze as much out as possible. I agree with doing `gzip -c9`; Brotli is a bit too futuristic for this test IMO because a lot of browsers don't support it yet. (And yes, thanks for voting it up in Edge. :))

**Comment by nolanlawson** [comment]
Added in #7.

**Comment by kennetpostigo** [comment]
Could Brotli compression be added as a plugin to webpack?
